### ISSUE TITLE
I need proxy

### ISSUE THREAD

**Issue by vuthanhtrung2010** [3V1/EzGen#2]
Hey how do i use proxy pls help!

**Comment by 3V1** [comment]
> Hey how do i use proxy pls help!
> 
> 

There is no proxy support. I do not plan on adding it either. Feel free to add it yourself.

**Comment by vuthanhtrung2010** [comment]
> > Hey how do i use proxy pls help!
> 
> There is no proxy support. I do not plan on adding it either. Feel free to add it yourself.

how do i add it teach me ;-;

**Comment by 3V1** [comment]
> > > Hey how do i use proxy pls help!
> 
> > 
> 
> > There is no proxy support. I do not plan on adding it either. Feel free to add it yourself.
> 
> 
> 
> how do i add it teach me ;-;

No, piss off.
